export const arenaCarsData = [
  {
    id: 1,
    name: 'Alto K10',
    logo: require('../assets/logos/alto-k10-logo.webp'),
    img: require('../assets/cars/alto-k10.webp'),
    price: '₹ 3,99 Lakh*',
    mileage: '24.90',
    power: '49 BHP',
    link: '/alto-k10-on-road-price-in-uttarpradesh',
  },
  {
    id: 2,
    name: 'Brezza',
    logo: require('../assets/logos/new-brezza.png'),
    img: require('../assets/cars/new-brezza.png'),
    price: '₹ 7,99 Lakh*',
    mileage: '17.0',
    power: '103.2 BHP',
    link: '/maruti-suzuki-brezza-on-road-price-in-uttarpradesh',
  },
  {
    id: 3,
    name: 'Alto',
    logo: require('../assets/logos/alto.png'),
    img: require('../assets/cars/Alto.png'),
    price: '₹ 4,07 Lakh*',
    mileage: '22.05',
    power: '47.3 BHP',
    link: '/alto-on-road-price-in-uttarpradesh',
  },

  {
    id: 4,
    name: 'Celerio',
    logo: require('../assets/logos/celerio.png'),
    img: require('../assets/cars/Celerio.png'),
    price: '₹ 5,24 Lakh*',
    mileage: '24.97',
    power: '65.71 BHP',
    link: '/all-new-celerio-on-road-price-in-uttarpradesh',
  },
  {
    id: 5,
    name: 'Dzire',
    logo: require('../assets/logos/dzire.png'),
    img: require('../assets/cars/Dzire.png'),
    price: '₹ 6,23 Lakh*',
    mileage: '23.26',
    power: '88.50 BHP',
    link: '/swift-dzire-on-road-price-in-uttarpradesh',
  },
  {
    id: 6,
    name: 'EECO',
    logo: require('../assets/logos/eeco.png'),
    img: require('../assets/cars/EECO.png'),
    price: '₹ 4,63 Lakh*',
    mileage: '16.11',
    power: '72.42 BHP',
    link: '/eeco-on-road-price-in-uttarpradesh',
  },
  {
    id: 7,
    name: 'Ertiga',
    logo: require('../assets/logos/ertiga.png'),
    img: require('../assets/cars/Ertiga.png'),
    price: '₹ 8,34 Lakh*',
    mileage: '20.51',
    power: '75.8 kW',
    link: '/maruti-ertiga-on-road-price-in-uttarpradesh',
  },
  {
    id: 8,
    name: 'Spresso',
    logo: require('../assets/logos/spresso.png'),
    img: require('../assets/cars/red.webp'),
    price: '₹ 3,99 Lakh*',
    mileage: '21.7',
    power: '67 BHP',
    link: '/maruti-suzuki-sspresso-cng-on-road-price-in-uttarpradesh',
  },
  {
    id: 9,
    name: 'Swift',
    logo: require('../assets/logos/swift.png'),
    img: require('../assets/cars/Swift.png'),
    price: '₹ 5,91 Lakh*',
    mileage: '23.20',
    power: '88.50 BHP',
    link: '/maruti-suzuki-swift-cng-on-road-price-in-uttarpradesh',
  },
  {
    id: 10,
    name: 'WagonR',
    logo: require('../assets/logos/wagonR.png'),
    img: require('../assets/cars/WagonR.png'),
    price: '₹ 5,47 Lakh*',
    mileage: '23.56',
    power: '88.50 BHP',
    link: '/wagonr-on-road-price-in-uttarpradesh',
  },
];

export const nexaCarsData = [
  {
    id: 1,
    name: 'Fronx',
    logo: require('../assets/nexa/Fronx/fronx-logo.webp'),
    img: require('../assets/nexa/Fronx/FRONX-Color-1500x700-NEXA_Blue.png'),
    price: 'Bookings Open',
    mileage: '-',
    power: '73.6',
    link: '/nexa-fronx-on-road-price-in-uttarpradesh',
  },
  {
   id: 2,
    name: 'Jimny',
    logo: require('../assets/nexa/Jimny/120x30+black.webp'),
    img: require('../assets/nexa/Jimny/smartwheels-jimny.png'),
    price: '₹ - Lakh*',
    mileage: '-',
    power: '73.6',
    link: '/nexa-jimny-on-road-price-in-uttarpradesh',
  },
  {
    id: 3,
    name: 'Grand Vitara',
    logo: require('../assets/logos/nexa/grand-vitara.webp'),
    img: require('../assets/logos/nexa/vehicles/rangeman_celestial_blue.webp'),
    price: '₹ 10.45 Lakh*',
    mileage: '27.97',
    power: '75.8 BHP',
    link: '/nexa-grand-vitara-on-road-price-in-uttarpradesh',
  },
  {
    id: 4,
    name: 'XL6',
    logo: require('../assets/logos/nexa/XL6.webp'),
    img: require('../assets/logos/nexa/vehicles/xl6.webp'),
    price: '₹ 11,29 Lakh*',
    mileage: '22.05',
    power: '47.3 BHP',
    link: '/nexa-xl6-on-road-price-in-uttarpradesh',
  },
  // {
  //   id: 3,
  //   name: "S-Cross",
  //   logo: require("../assets/logos/nexa/scross.webp"),
  //   img: require("../assets/logos/nexa/vehicles/scross.webp"),
  //   price: "₹ 8,95 Lakh",
  //   mileage: "17.0",
  //   power: "103.2 BHP",
  //   link: "/Scross",
  // },
  {
    id: 5,
    name: 'Ciaz',
    logo: require('../assets/logos/nexa/ciaz.webp'),
    img: require('../assets/logos/nexa/vehicles/ciaz.webp'),
    price: '₹ 8,99 Lakh*',
    mileage: '24.97',
    power: '65.71 BHP',
    link: '/nexa-ciaz-on-road-price-in-uttarpradesh',
  },
  {
    id: 6,
    name: 'Baleno',
    logo: require('../assets/logos/nexa/baleno.webp'),
    img: require('../assets/logos/nexa/vehicles/baleno.webp'),
    price: '₹ 6,49 Lakh*',
    mileage: '23.3',
    power: '88.50 BHP',
    link: '/nexa-baleno-on-road-price-in-uttarpradesh',
  },
  {
    id: 7,
    name: 'Ignis',
    logo: require('../assets/logos/nexa/ignis.webp'),
    img: require('../assets/logos/nexa/vehicles/ignis.webp'),
    price: '₹ 5,35 Lakh*',
    mileage: '16.11',
    power: '72.42 BHP',
    link: '/nexa-ignis-on-road-price-in-uttarpradesh',
  },
];

export const commercialCarsData = [
  {
    id: 1,
    name: 'Tour-S',
    logo: require('../assets/logos/commercial/Tour_S-logo.webp'),
    img: require('../assets/logos/commercial/dzire.png'),
    price: '₹ 7,16 Lakh*',
    mileage: '22.05',
    power: '47.3 BHP',
    link: '/maruti-dzire-tours-on-road-price-in-uttarpradesh',
  },
  {
    id: 2,
    name: 'Tour-H1',
    logo: require('../assets/logos/commercial/Tour_H1-logo.webp'),
    img: require('../assets/logos/commercial/alto800.png'),
    price: '₹ 4,05 Lakh*',
    mileage: '17.0',
    power: '103.2 BHP',
    link: '/maruti-alto-tourh1-on-road-price-in-uttarpradesh',
  },
  {
    id: 3,
    name: 'Tour-M',
    logo: require('../assets/logos/commercial/Tour_M-logo.webp'),
    img: require('../assets/logos/commercial/Tour-M.png'),
    price: '₹ 10,41 Lakh*',
    mileage: '24.97',
    power: '65.71 BHP',
    link: '/maruti-ertiga-tourm-on-road-price-in-uttarpradesh',
  },
  {
    id: 4,
    name: 'Tour-H3',
    logo: require('../assets/logos/commercial/Tour_H3-logo.webp'),
    img: require('../assets/logos/commercial/wagonr.webp'),
    price: '₹ 5,43 Lakh*',
    mileage: '23.3',
    power: '88.50 BHP',
    link: '/maruti-wagonr-tourh3-on-road-price-in-uttarpradesh',
  },
  {
    id: 5,
    name: 'Tour-V',
    logo: require('../assets/logos/commercial/Tour_V-logo.webp'),
    img: require('../assets/logos/commercial/tour-v.webp'),
    price: '₹ 5,91 Lakh*',
    mileage: '16.11',
    power: '72.42 BHP',
    link: '/maruti-eeco-tourhv-on-road-price-in-uttarpradesh',
  },
  {
    id: 6,
    name: 'Super Carry',
    logo: require('../assets/logos/supercarry_logo.webp'),
    img: require('../assets/commercial/supercarry/Super-Carry-for-range.png'),
    price: '₹ 5,93 Lakh*',
    mileage: '18',
    power: '72.42 BHP',
    link: '/maruti-super-carry-on-road-price-in-uttarpradesh',
  },
  {
    id: 6,
    name: 'Eeco Cargo',
    logo: require('../assets/logos/eecocargo.webp'),
    img: require('../assets/commercial/eecocargo/eeco-cargo.png'),
    price: '₹ 5,73 Lakh*',
    mileage: '20.00',
    power: '61.00 BHP',
    link: '/maruti-super-eeco-cargo-on-road-price-in-uttarpradesh',
  },
];
